INSERT INTO EPISODIO (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA, TITULO, DURACAO, DESCRICAO) VALUES
(1, 23, 'Partida x e x Companheiros', 24, 'Gon parte da Ilha da Baleia para se tornar um Hunter.'),
(2, 23, 'Exame x de x Exames', 24, 'Gon, Leorio e Kurapika enfrentam o primeiro teste de navegação.'),
(3, 23, 'Rivais x para x Sobrevivência', 24, 'A primeira fase do exame começa em um túnel interminável.'),
(4, 23, 'Esperança x e x Ambição', 24, 'Os candidatos atravessam o perigoso Pântano Numere.'),
(5, 23, 'Hisoka x é x Sorrateiro', 24, 'Hisoka demonstra seu poder letal contra outros candidatos.'),
(6, 23, 'Uma x Tarefa x Inesperada', 24, 'A segunda fase testa as habilidades culinárias dos Hunters.'),
(7, 23, 'Confronto x na x Aeronave', 24, 'Gon e Killua tentam tirar uma bola do Presidente Netero.'),
(8, 23, 'Decisão x pela x Maioria?', 24, 'O grupo entra na Torre de Truques e deve votar para avançar.'),
(9, 23, 'Cuidado x com x os x Prisioneiros', 24, 'Combates individuais contra criminosos condenados.'),
(10, 23, 'Truque x para x o x Truque', 24, 'Leorio perde tempo em uma aposta psicológica.'),
(11, 23, 'Aposta x de x Problema', 24, 'Killua mostra sua verdadeira face como assassino.'),
(12, 23, 'Último x Teste x de x Determinação', 24, 'O grupo precisa trabalhar junto para sair da torre.'),
(13, 23, 'Carta x de x Gon', 24, 'Recapitulação dos primeiros eventos (Episódio de resumo).'),
(14, 23, 'Atingir x o x Alvo', 24, 'A quarta fase começa na Ilha Zevil: caça aos crachás.'),
(15, 23, 'Explosão x de x Engano', 24, 'Gon treina sua paciência para roubar o crachá de Hisoka.'),
(16, 23, 'Derrota x e x Humilhação', 24, 'Gon consegue o crachá, mas aprende uma lição amarga.'),
(17, 23, 'Armadilha x na x Caverna', 24, 'O grupo fica preso em uma caverna cheia de cobras venenosas.'),
(18, 23, 'Uma x Entrevista x Importante', 24, 'Netero entrevista os finalistas antes da última fase.'),
(19, 23, 'Não x Pode x Vencer, x Mas x Não x Pode x Perder', 24, 'Gon enfrenta Hanzo em uma luta de resistência.'),
(20, 23, 'Reviravolta x Inesperada', 24, 'Killua é desclassificado após um encontro com seu irmão.'),
(21, 23, 'Problemas x de x Irmãos', 24, 'Gon decide ir até a Montanha Kukuroo buscar Killua.'),
(22, 23, 'Um x Cão x de x Guarda x Perigoso', 24, 'O grupo conhece Mike, o imenso cão de guarda dos Zoldyck.'),
(23, 23, 'O x Dever x de x um x Guarda', 24, 'Eles precisam passar pelo teste dos mordomos.'),
(24, 23, 'A x Família x Zoldyck', 24, 'Um olhar sobre a dinâmica interna da família de assassinos.'),
(25, 23, 'Não x Pode x Ver x se x Estiver x Cego', 24, 'Canary ajuda o grupo a avançar pela propriedade.'),
(26, 23, 'Antes x e x Depois', 24, 'Killua se liberta e o grupo se reúne finalmente.');


INSERT INTO EPISODIO (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA, TITULO, DURACAO, DESCRICAO) VALUES
(27, 23, 'Chegada x na x Arena', 24, 'Gon e Killua vão para a Arena Celestial para treinar e ganhar dinheiro.'),
(28, 23, 'Nen x e x Nen', 24, 'Eles conhecem Wing e começam a aprender sobre a energia vital.'),
(29, 23, 'Despertar x e x Potencial', 24, 'O batismo de Nen no 200º andar da arena.'),
(30, 23, 'Feroz x e x Ardente', 24, 'Gido usa seus piões reforçados com Nen contra Gon.'),
(31, 23, 'Destino x e x Tenacidade', 24, 'Gon aprende a importância da defesa no Nen.'),
(32, 23, 'Uma x Vitória x Surpreendente', 24, 'Killua enfrenta um adversário que usa eletricidade.'),
(33, 23, 'Uma x Ameaça x Vazia', 24, 'Hisoka observa o progresso dos meninos de longe.'),
(34, 23, 'Poder x para x Vingar', 24, 'Gon se prepara para devolver o crachá a Hisoka através de uma luta.'),
(35, 23, 'O x Verdadeiro x Exame', 24, 'A luta épica entre Gon e Hisoka começa.'),
(36, 23, 'Uma x Grande x Luta', 24, 'Gon consegue acertar um soco em Hisoka e encerra o arco.');

INSERT INTO EPISODIO (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA, TITULO, DURACAO, DESCRICAO) VALUES
(37, 23, 'Ging x e x Gon', 24, 'Gon volta para casa e descobre a fita deixada por seu pai.'),
(38, 23, 'Resposta x do x Pai', 24, 'A fita revela pistas sobre o jogo Greed Island.'),
(39, 23, 'Desejo x e x Promessa', 24, 'Kurapika busca emprego como guarda-costas para recuperar os olhos de seu clã.'),
(40, 23, 'Usuários x de x Nen x se x Unem?', 24, 'O teste de recrutamento para a máfia Nostrade.'),
(41, 23, 'Reunião x de x Heróis', 24, 'O grupo se encontra em Yorknew City para o leilão.'),
(42, 23, 'Defender x e x Atacar', 24, 'A Trupe Fantasma ataca o leilão e massacra os convidados.'),
(43, 23, 'Uma x Tragédia x Chocante', 24, 'Uvogin destrói as Bestas Sombrias da Máfia sozinho.'),
(44, 23, 'Acúmulo x de x Batalha', 24, 'Kurapika captura Uvogin usando suas novas correntes.'),
(45, 23, 'Restrição x e x Promessa', 24, 'A explicação sobre as condições mortais do Nen de Kurapika.'),
(46, 23, 'Perseguição x e x Espera', 24, 'A Trupe tenta resgatar seu membro capturado.'),
(47, 23, 'Condição x e x Juramento', 24, 'A luta mortal entre Kurapika e Uvogin.'),
(48, 23, 'Olhos x Muito x Afiados', 24, 'Gon e Killua tentam levantar dinheiro comprando itens raros.'),
(49, 23, 'Análise x e x Perseguição', 24, 'Eles começam a seguir os membros da Trupe Fantasma.'),
(50, 23, 'Aliados x e x Espadas', 24, 'Gon e Killua são capturados por Nobunaga e Machi.'),
(51, 23, 'Uma x Reunião x de x Sombras', 24, 'Chrollo Lucilfer, o líder, ordena um ataque em larga escala.'),
(52, 23, 'Ataque x e x Impacto', 24, 'Zeno e Silva Zoldyck são contratados para matar Chrollo.'),
(53, 23, 'Falso x e x Psíquico', 24, 'A Trupe forja suas próprias mortes usando cadáveres falsos.'),
(54, 23, 'Fortunas x Não x Estão x Certas?', 24, 'Chrollo lê o futuro dos membros através da poesia de Neon.'),
(55, 23, 'Aliados x e x Mentiras', 24, 'Kurapika descobre que a Trupe ainda está viva.'),
(56, 23, 'Amados x e x Oprimidos', 24, 'O plano para capturar o líder da Trupe começa.'),
(57, 23, 'Iniciativa x e x Lei', 24, 'Pakunoda deve escolher entre a vida do líder ou as regras da Trupe.'),
(58, 23, 'Sinal x para x Retirada', 24, 'O fim do conflito em Yorknew e a partida da Trupe.');

INSERT INTO EPISODIO (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA, TITULO, DURACAO, DESCRICAO) VALUES
(59, 23, 'Lance x e x Pressa', 24, 'O leilão de Greed Island começa.'),
(60, 23, 'Fim x e x Começo', 24, 'Gon e Killua são aceitos para jogar o jogo por Billionaire Tsezguerra.'),
(61, 23, 'Convite x e x Amigo', 24, 'Eles entram no mundo mágico de Greed Island.'),
(62, 23, 'Realidade x e x Brutos', 24, 'Eles aprendem que o jogo mata jogadores na vida real.'),
(63, 23, 'Uma x Mestra x Cruel', 24, 'Biscuit Krueger decide treinar os dois para valer.'),
(64, 23, 'Fortalecer x e x Ameaçar', 24, 'Treinamento intensivo de Shingen-Ryu.'),
(65, 23, 'Punho x de x Ferro x e x Tesoura', 24, 'Enfrentando o assassino Binolt para praticar combate.'),
(66, 23, 'Estratégia x e x Plano', 24, 'O plano para coletar as cartas raras do jogo.'),
(67, 23, '15 x e x 15', 24, 'Reunindo aliados para enfrentar o grupo de Genthru.'),
(68, 23, 'Piratas x e x Adivinhas', 24, 'O desafio esportivo contra os piratas de Razor.'),
(69, 23, 'Um x Confronto x de x Queimada', 24, 'O jogo de queimada mais mortal da história.'),
(70, 23, 'Sangue x e x Determinação', 24, 'Gon usa seu Jajanken para rebater a bola de Razor.'),
(71, 23, 'Poder x e x Estratégia', 24, 'A vitória contra os mestres do jogo.'),
(72, 23, 'Chase x e x Chance', 24, 'Genthru, o "Bombardeiro", revela sua identidade.'),
(73, 23, 'Insanidade x e x Sanidade', 24, 'Preparação final para a luta contra os bombardeiros.'),
(74, 23, 'Vencer x e x Perder', 24, 'Gon enfrenta Genthru em uma luta brutal de inteligência.'),
(75, 23, 'Amigos x de x Ging', 24, 'Eles completam o jogo e usam a carta de transporte.');

INSERT INTO EPISODIO (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA, TITULO, DURACAO, DESCRICAO) VALUES
(76, 23, 'Reunião x e x Entendimento', 24, 'Gon e Killua encontram Kite em vez de Ging.'),
(77, 23, 'Inquietude x e x Avistamento', 24, 'A Rainha das Formigas Quimera começa a se alimentar em NGL.'),
(78, 23, 'Reprodução x Muito x Rápida', 24, 'As formigas evoluem rapidamente e começam a usar armas e táticas.'),
(79, 23, 'NGL x Sem x Sorte', 24, 'Kite, Gon e Killua entram em NGL para investigar a infestação.'),
(80, 23, 'Mal x e x Terrível', 24, 'A história sombria de Gyro, o líder de NGL.'),
(81, 23, 'A x Luta x Começa', 24, 'O grupo de Kite enfrenta os primeiros capitães de divisão.'),
(82, 23, 'Kaito x e x Roleta', 24, 'Kite demonstra sua habilidade Nen: Crazy Slots.'),
(83, 23, 'Inspiração x para x Evoluir', 24, 'As formigas descobrem o poder do Nen após serem batizadas.'),
(84, 23, 'Um x Despertar x Fatal', 24, 'Neferpitou nasce e demonstra uma aura aterrorizante.'),
(85, 23, 'Luz x e x Escuridão', 24, 'Kite se sacrifica para que Gon e Killua possam fugir de Pitou.'),
(86, 23, 'Promessa x e x Reunião', 24, 'Gon e Killua treinam com Knuckle e Shoot para retornar a NGL.'),
(87, 23, 'Duelo x e x Fuga', 24, 'A luta contra Knuckle para testar a força de Gon.'),
(88, 23, 'Pedra-Papel-Tesoura x e x Fraqueza', 24, 'Gon aprimora seu Jajanken sob pressão.'),
(89, 23, 'Bondade x e x Força', 24, 'Bisky treina os meninos intensamente enquanto o tempo acaba.'),
(90, 23, 'Interesse x e x Maldição', 24, 'Killua luta contra sua própria hesitação e o medo implantado.'),
(91, 23, 'O x Forte x e x O x Fraco', 24, 'A seleção das formigas se torna mais cruel conforme o Rei nasce.'),
(92, 23, 'Um x Desejo x e x Dois x Juramentos', 24, 'O Rei Meruem nasce prematuramente, matando a Rainha.'),
(93, 23, 'Encontro x com x Palm', 24, 'Gon precisa sair em um encontro com Palm como parte de um acordo.'),
(94, 23, 'Amigo x e x Jornada', 24, 'Killua remove a agulha de Illumi de sua cabeça.'),
(95, 23, 'Rancor x e x Temor', 24, 'Gon e Killua se reúnem com a equipe de invasão de Netero.'),
(96, 23, 'Residência x Sem x Lei', 24, 'A Trupe Fantasma defende Meteor City de uma formiga invasora.'),
(97, 23, 'Carnificina x e x Devastação', 24, 'Feitan demonstra sua habilidade Pain Packer contra Zazan.'),
(98, 23, 'Infiltração x e x Seleção', 24, 'O plano para invadir o palácio do Rei em East Gorteau.'),
(99, 23, 'Combinação x e x Evolução', 24, 'Killua enfrenta os irmãos orca e polvo.'),
(100, 23, 'Rastreamento x e x Perseguição', 24, 'Gon faz amizade com a formiga Meleoron.'),
(101, 23, 'Ikalgo x e x Relâmpago', 24, 'Killua salva Ikalgo e ganha um aliado inesperado.'),
(102, 23, 'Poder x e x Jogos', 24, 'Meruem começa a jogar Gungi contra a campeã Komugi.'),
(103, 23, 'Checkmate x e x Leitura', 24, 'O Rei não consegue vencer Komugi e começa a mudar.'),
(104, 23, 'Hesitação x e x Solução', 24, 'A invasão do palácio está prestes a começar.'),
(105, 23, 'Zênite x e x Alarme', 24, 'Netero e Zeno chegam montados em um dragão de Nen.'),
(106, 23, 'Retorno x e x Retirada', 24, 'Knuckle enfrenta Menthuthuyoupi.'),
(107, 23, 'Retorno x e x Ikalgo', 24, 'Ikalgo executa sua missão infiltrada no subsolo.'),
(108, 23, 'Gungi x de x Komugi', 24, 'O Rei protege Komugi ferida, confundindo seus guardas.'),
(109, 23, 'Marcha x e x Intrusão', 24, 'Gon finalmente fica cara a cara com Neferpitou.'),
(110, 23, 'Confusão x e x Expectativa', 24, 'Pitou está curando Komugi, e Gon é forçado a esperar.'),
(111, 23, 'Ataque x e x Invasão', 24, 'A narração detalha os segundos iniciais da batalha no palácio.'),
(112, 23, 'Monstro x e x Monstro', 24, 'Zeno e Netero se separam para levar o Rei ao campo de batalha.'),
(113, 23, 'Um x Inseto x Indebitado', 24, 'Shoot demonstra coragem incrível contra Youpi.'),
(114, 23, 'Dividir x e x Conquistar', 24, 'Knuckle tenta usar o JAPR para falir o Nen de Youpi.'),
(115, 23, 'Dever x e x Pergunta', 24, 'Meleoron e Knuckle usam o Perfect Plan para atacar.'),
(116, 23, 'Vingança x e x Recuperação', 24, 'A fúria de Gon explode ao ver Pitou protegendo alguém.'),
(117, 23, 'Insulto x e x Vingança', 24, 'Knuckle enfrenta o dilema de desativar seu poder.'),
(118, 23, 'Falsa x Raiva', 24, 'Youpi descobre novas formas de transformar sua fúria.'),
(119, 23, 'Forte x ou x Fraco', 24, 'Killua intervém com sua velocidade Godspeed.'),
(120, 23, 'Falso x e x Verdadeiro', 24, 'A batalha psicológica entre Pouf e Morel.'),
(121, 23, 'Derrota x e x Dignidade', 24, 'Youpi poupa a vida de Knuckle e Morel.'),
(122, 23, 'Pose x e x Nome', 24, 'Netero revela o nome do Rei: Meruem.'),
(123, 23, 'Centopéia x e x Memória', 24, 'Welfin confronta seus sentimentos sobre Gyro.'),
(124, 23, 'Ruptura x e x Despertar', 24, 'Palm é transformada em formiga mas recupera sua consciência.'),
(125, 23, 'Grande x Iluminação x e x Destruição', 24, 'Netero usa a Mão Zero contra o Rei.'),
(126, 23, 'Poder x Zero x e x Poder x Rose', 24, 'O sacrifício final de Netero com a bomba Rose.'),
(127, 23, 'Hostilidade x e x Determinação', 24, 'Pouf e Youpi encontram o Rei à beira da morte.'),
(128, 23, 'Alegria x Incomparável', 24, 'O Rei renasce mais forte após consumir parte de seus guardas.'),
(129, 23, 'Alvo x e x Mentira', 24, 'Meruem sofre de amnésia temporária sobre Komugi.'),
(130, 23, 'Magia x e x Desespero', 24, 'Pitou leva Gon até onde Kite está para "curá-lo".'),
(131, 23, 'Ira x e x Luz', 24, 'Gon faz o pacto supremo para derrotar Pitou.'),
(132, 23, 'Flash x e x Começo', 24, 'O Rei retorna ao palácio com poderes divinos.'),
(133, 23, 'Prazo x para x Viver', 24, 'Welfin revela a palavra "Komugi", restaurando a memória do Rei.'),
(134, 23, 'Apenas x uma x Palavra', 24, 'O veneno da Rose começa a afetar a todos.'),
(135, 23, 'Este x Dia x e x Este x Momento', 24, 'A despedida final entre Meruem e Komugi.'),
(136, 23, 'Regresso x a x Casa x e x Nome x Verdadeiro', 24, 'As formigas sobreviventes tentam encontrar seu lugar no mundo.');


INSERT INTO EPISODIO (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA, TITULO, DURACAO, DESCRICAO) VALUES
(137, 23, 'Debate x entre x os x Zodíacos', 24, 'Os 12 Zodíacos se reúnem para decidir a sucessão de Netero.'),
(138, 23, 'Pedido x e x Desejo', 24, 'Killua volta para casa para buscar Alluka e salvar Gon.'),
(139, 23, 'Alluka x e x Nanika', 24, 'A explicação sobre os poderes aterrorizantes e bondosos de Alluka.'),
(140, 23, 'Eleição x e x Batalha', 24, 'Illumi persegue Killua para controlar o poder de Alluka.'),
(141, 23, 'Mágico x e x Mordomo', 24, 'Hisoka ajuda Illumi enquanto Killua foge com Alluka.'),
(142, 23, 'Agulha x e x Caça', 24, 'Killua usa o Godspeed para atravessar o país rapidamente.'),
(143, 23, 'Pecado x e x Garra', 24, 'Leorio dá um soco em Ging durante a assembleia dos Hunters.'),
(144, 23, 'Aprovação x e x Coalizão', 24, 'A eleição chega aos estágios finais com Leorio ganhando apoio.'),
(145, 23, 'Derrota x e x Reunião', 24, 'Gon é curado e aparece no auditório da eleição.'),
(146, 23, 'Presidente x e x Liberação', 24, 'Pariston vence a eleição mas renuncia imediatamente.'),
(147, 23, 'Salvação x e x Futuro', 24, 'Gon se despede de Killua e Alluka.'),
(148, 23, 'Passado x e x Futuro', 24, 'Gon e Ging conversam sobre o que realmente importa na jornada.');