CREATE TABLE ADMIN (
    ID_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    DT_CADASTRO DATE DEFAULT (CURRENT_DATE),
    FK_TELEFONE_TELEFONE_PK INT,
    FOREIGN KEY (FK_TELEFONE_TELEFONE_PK) REFERENCES TELEFONE(TELEFONE_PK) ON DELETE SET NULL
);

ALTER TABLE FILME
ADD COLUMN ASSISTIDO BOOLEAN DEFAULT FALSE,
ADD COLUMN FK_USUARIO_ID_USER INT;

ALTER TABLE FILME
ADD CONSTRAINT fk_filme_usuario
FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE SET NULL;

ALTER TABLE SERIE
ADD COLUMN ASSISTIDO BOOLEAN DEFAULT FALSE,
ADD COLUMN FK_USUARIO_ID_USER INT;

ALTER TABLE SERIE
ADD CONSTRAINT fk_serie_usuario
FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE SET NULL;

ALTER TABLE SERIE DROP COLUMN STATUS;