INSERT INTO TELEFONE (TELEFONE) VALUES ('79999999999');

INSERT INTO ADMIN (NOME, EMAIL, SENHA, DT_CADASTRO, FK_TELEFONE_TELEFONE_PK) 
VALUES (
    'admin',
    'admin@gmail.com',
    'admin',
    CURRENT_DATE(), 
    (SELECT TELEFONE_PK FROM TELEFONE WHERE TELEFONE = '79999999999')
);