CREATE OR REPLACE VIEW vw_avaliacoes_recentes AS
SELECT
    a.ID_AVALIACAO,
    a.NOTA,
    a.COMENTARIO,
    a.DATA_AVALIACAO,
    u.ID_USER AS ID_USUARIO,
    u.NOME AS AVALIADOR,
    a.FK_FILME_ID_MIDIA AS ID_FILME,
    a.FK_SERIE_ID_MIDIA AS ID_SERIE
FROM AVALIACAO a
JOIN USUARIO u ON a.FK_USUARIO_ID_USER = u.ID_USER
ORDER BY a.DATA_AVALIACAO DESC;