CREATE OR REPLACE VIEW vw_avaliacoes_positivas_com_genero AS
SELECT f.ID_MIDIA, f.POSTER_URL, f.ANO_LANCAMENTO, u.NOME AS Avaliador, f.TITULO AS Filme, p.NOME_GENERO AS Genero, a.NOTA, a.COMENTARIO
FROM AVALIACAO a
JOIN USUARIO u ON a.FK_USUARIO_ID_USER = u.ID_USER
JOIN FILME f ON a.FK_FILME_ID_MIDIA = f.ID_MIDIA
JOIN PERTENCER p ON f.ID_MIDIA = p.FK_FILME_ID_MIDIA
WHERE a.NOTA >= 4.0;

CREATE OR REPLACE VIEW vw_filmes_aclamados_bilheteria AS
SELECT f.ID_MIDIA, f.POSTER_URL, f.TITULO, f.BILHETERIA, f.NOTA_IMDB, p.NOME_GENERO
FROM FILME f
JOIN PERTENCER p ON f.ID_MIDIA = p.FK_FILME_ID_MIDIA
WHERE f.NOTA_IMDB > (SELECT AVG(NOTA_IMDB) FROM FILME WHERE NOTA_IMDB IS NOT NULL);