CREATE TABLE TELEFONE (
    TELEFONE_PK INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONE VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE USUARIO (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    DT_CADASTRO DATE DEFAULT (CURRENT_DATE),
    FK_TELEFONE_TELEFONE_PK INT,
    FOREIGN KEY (FK_TELEFONE_TELEFONE_PK) REFERENCES TELEFONE(TELEFONE_PK) ON DELETE SET NULL
);

CREATE TABLE SEGUE (
    FK_USUARIO_ID_USER INT,
    FK_USUARIO_ID_USER_ INT,
    PRIMARY KEY (FK_USUARIO_ID_USER, FK_USUARIO_ID_USER_),
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (FK_USUARIO_ID_USER_) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    CHECK (FK_USUARIO_ID_USER <> FK_USUARIO_ID_USER_)
);

CREATE TABLE LISTA (
    ID_LISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_LISTA VARCHAR(100) NOT NULL
);

CREATE TABLE CRIA (
    FK_LISTA_ID_LISTA INT,
    FK_USUARIO_ID_USER INT,
    PRIMARY KEY (FK_LISTA_ID_LISTA, FK_USUARIO_ID_USER),
    FOREIGN KEY (FK_LISTA_ID_LISTA) REFERENCES LISTA(ID_LISTA) ON DELETE CASCADE,
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE
);

CREATE TABLE FILME (
    ID_MIDIA INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    BILHETERIA DECIMAL(15,2),
    DURACAO INT CHECK (DURACAO > 0),
    ANO_LANCAMENTO INT CHECK (ANO_LANCAMENTO > 1800),
    PAIS_ORIGEM VARCHAR(50),
    AVALIACAO DECIMAL(3,1) DEFAULT 0.0 CHECK (AVALIACAO >= 0 AND AVALIACAO <= 10),
    DATA_INCLUSAO DATE DEFAULT (CURRENT_DATE),
    FK_USUARIO_ID_USER INT,
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE SET NULL
);

CREATE TABLE SERIE (
    ID_MIDIA INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    STATUS VARCHAR(50) DEFAULT 'Em Lançamento' CHECK (STATUS IN ('Em Lançamento', 'Finalizada', 'Cancelada')),
    QTD_TEMPORADAS INT DEFAULT 1 CHECK (QTD_TEMPORADAS > 0),
    ANO_LANCAMENTO INT CHECK (ANO_LANCAMENTO > 1800),
    PAIS_ORIGEM VARCHAR(50),
    AVALIACAO DECIMAL(3,1) DEFAULT 0.0,
    DATA_INCLUSAO DATE DEFAULT (CURRENT_DATE),
    FK_USUARIO_ID_USER INT,
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE SET NULL
);

CREATE TABLE TEMPORADA (
    ID_TEMPORADA INT AUTO_INCREMENT PRIMARY KEY,
    FK_SERIE_ID_MIDIA INT NOT NULL,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE
);

CREATE TABLE EPISODIO (
    NUM_EPISODIO INT,
    FK_TEMPORADA_ID_TEMPORADA INT,
    TITULO VARCHAR(255),
    DURACAO INT CHECK (DURACAO > 0),
    PRIMARY KEY (NUM_EPISODIO, FK_TEMPORADA_ID_TEMPORADA),
    FOREIGN KEY (FK_TEMPORADA_ID_TEMPORADA) REFERENCES TEMPORADA(ID_TEMPORADA) ON DELETE CASCADE
);

CREATE TABLE GENERO (
    NOME_GENERO VARCHAR(50) PRIMARY KEY
);

CREATE TABLE PLATAFORMA (
    ID_PLATAFORMA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE,
    URL VARCHAR(255)
);

CREATE TABLE PESSOA (
    ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    PESSOA_TIPO INT CHECK (PESSOA_TIPO IN (1, 2, 3))
);

CREATE TABLE PERTENCER (
    ID_PERTENCER INT AUTO_INCREMENT PRIMARY KEY,
    NOME_GENERO VARCHAR(50) NOT NULL,
    FK_FILME_ID_MIDIA INT,
    FK_SERIE_ID_MIDIA INT,
    FOREIGN KEY (NOME_GENERO) REFERENCES GENERO(NOME_GENERO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FK_FILME_ID_MIDIA) REFERENCES FILME(ID_MIDIA) ON DELETE CASCADE,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE,
    CHECK (
        (FK_FILME_ID_MIDIA IS NOT NULL AND FK_SERIE_ID_MIDIA IS NULL) OR
        (FK_FILME_ID_MIDIA IS NULL AND FK_SERIE_ID_MIDIA IS NOT NULL)
    )
);

CREATE TABLE CONTEM (
    ID_CONTEM INT AUTO_INCREMENT PRIMARY KEY,
    FK_LISTA_ID_LISTA INT NOT NULL,
    FK_FILME_ID_MIDIA INT,
    FK_SERIE_ID_MIDIA INT,
    FOREIGN KEY (FK_LISTA_ID_LISTA) REFERENCES LISTA(ID_LISTA) ON DELETE CASCADE,
    FOREIGN KEY (FK_FILME_ID_MIDIA) REFERENCES FILME(ID_MIDIA) ON DELETE CASCADE,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE,
    CHECK (
        (FK_FILME_ID_MIDIA IS NOT NULL AND FK_SERIE_ID_MIDIA IS NULL) OR
        (FK_FILME_ID_MIDIA IS NULL AND FK_SERIE_ID_MIDIA IS NOT NULL)
    )
);

CREATE TABLE DISPONIVEL (
    ID_DISPONIVEL INT AUTO_INCREMENT PRIMARY KEY,
    FK_PLATAFORMA_ID_PLATAFORMA INT NOT NULL,
    FK_FILME_ID_MIDIA INT,
    FK_SERIE_ID_MIDIA INT,
    FOREIGN KEY (FK_PLATAFORMA_ID_PLATAFORMA) REFERENCES PLATAFORMA(ID_PLATAFORMA) ON DELETE CASCADE,
    FOREIGN KEY (FK_FILME_ID_MIDIA) REFERENCES FILME(ID_MIDIA) ON DELETE CASCADE,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE,
    CHECK (
        (FK_FILME_ID_MIDIA IS NOT NULL AND FK_SERIE_ID_MIDIA IS NULL) OR
        (FK_FILME_ID_MIDIA IS NULL AND FK_SERIE_ID_MIDIA IS NOT NULL)
    )
);

CREATE TABLE ATUAR (
    ID_ATUAR INT AUTO_INCREMENT PRIMARY KEY,
    FK_PESSOA_ID_PESSOA INT NOT NULL,
    FK_FILME_ID_MIDIA INT,
    FK_SERIE_ID_MIDIA INT,
    FOREIGN KEY (FK_PESSOA_ID_PESSOA) REFERENCES PESSOA(ID_PESSOA) ON DELETE CASCADE,
    FOREIGN KEY (FK_FILME_ID_MIDIA) REFERENCES FILME(ID_MIDIA) ON DELETE CASCADE,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE,
    CHECK (
        (FK_FILME_ID_MIDIA IS NOT NULL AND FK_SERIE_ID_MIDIA IS NULL) OR
        (FK_FILME_ID_MIDIA IS NULL AND FK_SERIE_ID_MIDIA IS NOT NULL)
    )
);

CREATE TABLE DIRIGIR (
    ID_DIRIGIR INT AUTO_INCREMENT PRIMARY KEY,
    FK_PESSOA_ID_PESSOA INT NOT NULL,
    FK_FILME_ID_MIDIA INT,
    FK_SERIE_ID_MIDIA INT,
    FOREIGN KEY (FK_PESSOA_ID_PESSOA) REFERENCES PESSOA(ID_PESSOA) ON DELETE CASCADE,
    FOREIGN KEY (FK_FILME_ID_MIDIA) REFERENCES FILME(ID_MIDIA) ON DELETE CASCADE,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE,
    CHECK (
        (FK_FILME_ID_MIDIA IS NOT NULL AND FK_SERIE_ID_MIDIA IS NULL) OR
        (FK_FILME_ID_MIDIA IS NULL AND FK_SERIE_ID_MIDIA IS NOT NULL)
    )
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIO_ID_USER INT NOT NULL,
    FK_FILME_ID_MIDIA INT,
    FK_SERIE_ID_MIDIA INT,
    NOTA DECIMAL(3,1) CHECK (NOTA >= 0 AND NOTA <= 5),
    COMENTARIO TEXT,
    DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (FK_FILME_ID_MIDIA) REFERENCES FILME(ID_MIDIA) ON DELETE CASCADE,
    FOREIGN KEY (FK_SERIE_ID_MIDIA) REFERENCES SERIE(ID_MIDIA) ON DELETE CASCADE,
    CHECK (
        (FK_FILME_ID_MIDIA IS NOT NULL AND FK_SERIE_ID_MIDIA IS NULL) OR
        (FK_FILME_ID_MIDIA IS NULL AND FK_SERIE_ID_MIDIA IS NOT NULL)
    )
);

CREATE TABLE INTERAGIR (
    FK_USUARIO_ID_USER INT NOT NULL,
    FK_AVALIACAO_ID INT NOT NULL,
    PRIMARY KEY (FK_USUARIO_ID_USER, FK_AVALIACAO_ID),
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (FK_AVALIACAO_ID) REFERENCES AVALIACAO(ID_AVALIACAO) ON DELETE CASCADE
);