
INSERT INTO GENERO (NOME_GENERO) VALUES
    ('Ação'),
    ('Comédia'),
    ('Drama'),
    ('Ficção Científica'),
    ('Terror'),
    ('Romance'),
    ('Fantasia');


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0377092';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0377092';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0499549';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0499549';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0499549';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt18925334';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt18925334';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt14205554';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt14205554';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt14205554';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt13238346';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt13238346';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt28156629';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0097165';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0327597';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0327597';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0112697';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0112697';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0372784';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0372784';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt18351128';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt18351128';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0251127';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0251127';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0096283';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0876563';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0876563';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt1099212';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt1099212';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0293508';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0293508';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0266697';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0947798';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0947798';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt33549683';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt33549683';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt33549683';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt5950044';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt5950044';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt5052448';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt1119646';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt1375666';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt1375666';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt6751668';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0101414';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0101414';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt31193180';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt31193180';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0109830';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0109830';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0109830';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0137523';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0468569';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0468569';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', ID_MIDIA, NULL FROM FILME WHERE ID_IMDB = 'tt0068646';