
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt14452776';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt14452776';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5421602';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5421602';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt6134640';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0903747';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt7335184';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt7335184';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt7335184';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt7366338';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt10048342';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5180504';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5180504';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5180504';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt27497448';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt27497448';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt27497448';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt11126994';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt11126994';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt11126994';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt11126994';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt19244304';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt19244304';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt8772296';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt3581920';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt3581920';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt3581920';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0460681';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0460681';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0460681';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0397442';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Romance', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0397442';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0397442';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0279600';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0279600';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0279600';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0147746';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0147746';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0147746';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2356777';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0877057';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0877057';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2560140';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2560140';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2560140';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt12343534';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt12343534';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0421357';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0421357';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0421357';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2098220';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2098220';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0098936';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0098936';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt3322312';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt3322312';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2287229';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5753856';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5753856';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Terror', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt5753856';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt1442437';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt1442437';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ação', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0944947';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0944947';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Drama', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt0944947';


INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Ficção Científica', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2861424';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Comédia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2861424';
INSERT INTO PERTENCER (NOME_GENERO, FK_FILME_ID_MIDIA, FK_SERIE_ID_MIDIA)
SELECT 'Fantasia', NULL, ID_MIDIA FROM SERIE WHERE ID_IMDB = 'tt2861424';