CREATE TABLE COMENTARIO_AVALIACAO (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    FK_AVALIACAO_ID INT NOT NULL,
    FK_USUARIO_ID_USER INT NOT NULL,
    TEXTO TEXT NOT NULL,
    DATA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_AVALIACAO_ID) REFERENCES AVALIACAO(ID_AVALIACAO) ON DELETE CASCADE,
    FOREIGN KEY (FK_USUARIO_ID_USER) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE
);