CREATE TRIGGER atualiza_media_filme_delete
AFTER DELETE ON AVALIACAO
FOR EACH ROW
BEGIN
    IF OLD.FK_FILME_ID_MIDIA IS NOT NULL THEN
        UPDATE FILME
        SET AVALIACAO = (
            SELECT COALESCE(AVG(NOTA), 0)
            FROM AVALIACAO
            WHERE FK_FILME_ID_MIDIA = OLD.FK_FILME_ID_MIDIA
        )
        WHERE ID_MIDIA = OLD.FK_FILME_ID_MIDIA;
    END IF;
END;


CREATE TRIGGER atualiza_media_serie_delete
AFTER DELETE ON AVALIACAO
FOR EACH ROW
BEGIN
    IF OLD.FK_SERIE_ID_MIDIA IS NOT NULL THEN
        UPDATE SERIE
        SET AVALIACAO = (
            SELECT COALESCE(AVG(NOTA), 0)
            FROM AVALIACAO
            WHERE FK_SERIE_ID_MIDIA = OLD.FK_SERIE_ID_MIDIA
        )
        WHERE ID_MIDIA = OLD.FK_SERIE_ID_MIDIA;
    END IF;
END;