ALTER TABLE FILME
ADD COLUMN ID_IMDB VARCHAR(20) UNIQUE NOT NULL AFTER ID_MIDIA,
ADD COLUMN POSTER_URL VARCHAR(255) AFTER TITULO,
ADD COLUMN NOTA_IMDB DECIMAL(3,1) AFTER AVALIACAO;

ALTER TABLE SERIE
ADD COLUMN ID_IMDB VARCHAR(20) UNIQUE NOT NULL AFTER ID_MIDIA,
ADD COLUMN POSTER_URL VARCHAR(255) AFTER TITULO,
ADD COLUMN NOTA_IMDB DECIMAL(3,1) AFTER AVALIACAO;