INSERT INTO SERIE (STATUS, QTD_TEMPORADAS, ID_IMDB, TITULO, DESCRICAO, POSTER_URL, NOTA_IMDB, ANO_LANCAMENTO, AVALIACAO) VALUES
('Finalizada', 5, 'tt14452776', 'The Bear', 'Um jovem chef do mundo da alta gastronomia retorna a Chicago para administrar a lanchonete de sua família.', 'https://m.media-amazon.com/images/M/MV5BYWZhNDZiMzAtZmZlYS00MWFmLWE2MWEtNDAxZTZiN2U4Y2U2XkEyXkFqcGc@._V1_SX300.jpg', 8.5, 2022, 0),
('Finalizada', 3, 'tt5421602', 'Anne with an E', 'As aventuras de uma jovem órfã no final do século XIX. Acompanhe Anne enquanto ela aprende a navegar em sua nova vida na Ilha do Príncipe Eduardo.', 'https://m.media-amazon.com/images/M/MV5BZWUzZGM1OTYtMWUyNS00NTBmLTg1YTMtOTllMWFmYjk2NGU2XkEyXkFqcGc@._V1_SX300.jpg', 8.6, 2017, 0),
('Finalizada', 2, 'tt6134640', 'Mindhunter', 'Pegar um criminoso muitas vezes exige que as autoridades entrem na mente do vilão. Esse é o trabalho dos agentes do FBI Holden Ford e Bill Tench.', NULL, 8.7, 2017, 0),
('Finalizada', 5, 'tt0903747', 'Breaking Bad', 'Um professor de química diagnosticado com câncer de pulmão inoperável passa a fabricar e vender metanfetamina para garantir o futuro de sua família.', 'https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_SX300.jpg', 9.5, 2008, 0),
('Finalizada', 5, 'tt7335184', 'You', 'Um jovem charmoso e intenso se insere na vida de mulheres que o fascinam.', 'https://m.media-amazon.com/images/M/MV5BMTVlYmRhMWQtNmE0Yi00ODM1LWEzMWEtNTQzZGZhODRmZTE0XkEyXkFqcGc@._V1_SX300.jpg', 7.6, 2018, 0),
('Finalizada', 1, 'tt7366338', 'Chernobyl', 'Em abril de 1986, a cidade de Chernobyl sofre um dos piores desastres nucleares da história. Muitos heróis arriscam suas vidas nos meses seguintes.', 'https://m.media-amazon.com/images/M/MV5BNzU0OTI4YTQtNGQ1ZS00ZjA4LTg3MTMtZjkyZWNjN2RiZDJmXkEyXkFqcGc@._V1_SX300.jpg', 9.3, 2019, 0),
('Finalizada', 1, 'tt10048342', 'O Gambito da Rainha', 'Órfã aos nove anos, a prodígio Beth Harmon domina o xadrez nos EUA dos anos 60, mas o estrelato infantil tem um preço.', 'https://m.media-amazon.com/images/M/MV5BMmRlNjQxNWQtMjk1OS00N2QxLTk0YWQtMzRhYjY5YTFhNjMxXkEyXkFqcGc@._V1_SX300.jpg', 8.5, 2020, 0),
('Finalizada', 4, 'tt5180504', 'The Witcher', 'Geralt de Rivia, um caçador de monstros solitário, luta para encontrar seu lugar em um mundo onde as pessoas costumam ser mais perversas que as feras.', 'https://m.media-amazon.com/images/M/MV5BOTQzMzNmMzUtODgwNS00YTdhLTg5N2MtOWU1YTc4YWY3NjRlXkEyXkFqcGc@._V1_SX300.jpg', 7.9, 2019, 0),
('Finalizada', 1, 'tt27497448', 'A Knight of the Seven Kingdoms', 'Um século antes de GOT, Sor Duncan o Alto e seu escudeiro, Egg, vagam por Westeros enquanto a dinastia Targaryen governa o Trono de Ferro.', 'https://m.media-amazon.com/images/M/MV5BNGUxNDM5OTEtZWRiYi00OWI1LTgxOTctYzljYTJmMjlkY2Y4XkEyXkFqcGc@._V1_SX300.jpg', NULL, 2026, 0),
('Finalizada', 2, 'tt11126994', 'Arcane', 'Em meio à discórdia entre as cidades de Piltover e Zaun, duas irmãs lutam em lados opostos de uma guerra de tecnologias mágicas.', 'https://m.media-amazon.com/images/M/MV5BYjA2NzhlMDItNWRmZC00MzRjLWE3ZjAtZjBlZDAwOWY2ODdjXkEyXkFqcGc@._V1_SX300.jpg', 9.0, 2021, 0),
('Finalizada', 1, 'tt19244304', 'IT: Bem-vindo a Derry', 'Em 1962, um casal se muda para Derry exatamente quando um menino desaparece. Com sua chegada, coisas terríveis começam a acontecer.', 'https://m.media-amazon.com/images/M/MV5BZWE0ZWM1MjUtNmYzYS00NzU3LTkxYmQtNmI3NTc0ZTY1NmVlXkEyXkFqcGc@._V1_SX300.jpg', 8.0, 2025, 0),
('Finalizada', 3, 'tt8772296', 'Euphoria', 'Um grupo de adolescentes experimenta os altos e baixos do amor e da amizade em um mundo de redes sociais, sexo, drogas e violência.', 'https://m.media-amazon.com/images/M/MV5BZjVlN2M2N2MtOWViZC00MzIxLTlhZWEtMTIwNDIwMzE3ZWJiXkEyXkFqcGc@._V1_SX300.jpg', 8.2, 2019, 0),
('Finalizada', 2, 'tt3581920', 'The Last of Us', 'Após uma pandemia global destruir a civilização, um sobrevivente endurecido assume o controle de uma garota que pode ser a última esperança da humanidade.', 'https://m.media-amazon.com/images/M/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_SX300.jpg', 8.5, 2023, 0),
('Finalizada', 15, 'tt0460681', 'Supernatural', 'Dois irmãos seguem os passos do pai como caçadores, combatendo seres sobrenaturais malignos de todos os tipos que vagam pela terra.', 'https://m.media-amazon.com/images/M/MV5BMDFmMGZmMGItNGRjNC00NjVjLWI5ODEtNzhjMTE5MmJhN2FkXkEyXkFqcGc@._V1_SX300.jpg', 8.4, 2005, 0),
('Finalizada', 6, 'tt0397442', 'Gossip Girl', 'Narrado por uma blogueira misteriosa, segue adolescentes ricos em suas vidas escandalosas como a elite de Manhattan.', 'https://m.media-amazon.com/images/M/MV5BZDljNzZmMGMtM2FmNC00ZTkzLTg2OTctNDAxZGViYjVlYjAxXkEyXkFqcGc@._V1_SX300.jpg', 7.5, 2007, 0),
('Finalizada', 10, 'tt0279600', 'Smallville', 'O jovem Clark Kent luta para encontrar seu lugar no mundo enquanto aprende a usar seus poderes alienígenas para o bem.', 'https://m.media-amazon.com/images/M/MV5BZDU0ZDVjOTItMDNkMy00YTI0LWFjYzItY2M1NjU5NjAzZGViXkEyXkFqcGc@._V1_SX300.jpg', 7.5, 2001, 0),
('Finalizada', 3, 'tt0147746', 'Batman do Futuro', 'Movido por remorso e vingança, Terry McGinnis assume o papel de Batman sob a supervisão de um idoso Bruce Wayne em uma Gotham futurista.', 'https://m.media-amazon.com/images/M/MV5BMDExYjNiYTYtZDkwZC00NDcxLTk3YWYtMmIyN2ZlZGYyY2E0XkEyXkFqcGc@._V1_SX300.jpg', 8.1, 1999, 0),
('Finalizada', 4, 'tt2356777', 'True Detective', 'Série de antologia na qual investigações policiais revelam segredos pessoais e profissionais dos envolvidos, dentro e fora da lei.', 'https://m.media-amazon.com/images/M/MV5BYjgwYzA1NWMtNDYyZi00ZGQyLWI5NTktMDYwZjE2OTIwZWEwXkEyXkFqcGc@._V1_SX300.jpg', 8.8, 2014, 0);

INSERT INTO SERIE (STATUS, QTD_TEMPORADAS, ID_IMDB, TITULO, DESCRICAO, POSTER_URL, NOTA_IMDB, ANO_LANCAMENTO, AVALIACAO) VALUES
('Finalizada', 1, 'tt0877057', 'Death Note', 'Um estudante inteligente do ensino médio inicia uma cruzada secreta para eliminar criminosos do mundo após descobrir um caderno capaz de matar qualquer pessoa cujo nome seja escrito nele.', 'https://m.media-amazon.com/images/M/MV5BYTgyZDhmMTEtZDFhNi00MTc4LTg3NjUtYWJlNGE5Mzk2NzMxXkEyXkFqcGc@._V1_SX300.jpg', 8.9, 2006, 0),
('Finalizada', 4, 'tt2560140', 'Attack on Titan', 'Em um mundo onde a humanidade se abriga atrás de muralhas gigantescas contra Titãs devoradores de homens, um jovem determinado se junta à elite do Corpo de Exploração para lutar contra os gigantes.', 'https://m.media-amazon.com/images/M/MV5BZjliODY5MzQtMmViZC00MTZmLWFhMWMtMjMwM2I3OGY1MTRiXkEyXkFqcGc@._V1_SX300.jpg', 9.1, 2013, 0),
('Finalizada', 3, 'tt12343534', 'Jujutsu Kaisen', 'Um garoto engole um talismã amaldiçoado — o dedo de um demônio — e se torna amaldiçoado. Ele entra em uma escola de feiticeiros para localizar as outras partes do corpo do demônio e exorcizar a si mesmo.', 'https://m.media-amazon.com/images/M/MV5BMjBlNTExMDAtMWZjZi00MDc5LWFkMjgtZDU0ZWQ5ODk3YWY5XkEyXkFqcGc@._V1_SX300.jpg', 8.5, 2020, 0),
('Finalizada', 1, 'tt0421357', 'Fullmetal Alchemist', 'Quando um ritual alquímico fracassado deixa os irmãos Edward e Alphonse Elric com corpos severamente danificados, eles começam a buscar a única coisa que pode salvá-los: a lendária Pedra Filosofal.', 'https://m.media-amazon.com/images/M/MV5BNDczZWMyMjEtZDI0ZS00YThjLWE2MjEtNTIxNmVmZDhkNDg5XkEyXkFqcGc@._V1_SX300.jpg', 8.5, 2003, 0),
('Finalizada', 1, 'tt2098220', 'Hunter x Hunter', 'Gon Freecss aspira tornar-se um Hunter, um ser excepcional capaz de grandeza. Com seus amigos e seu potencial, ele busca encontrar seu pai, que o deixou quando ele era mais jovem.', 'https://m.media-amazon.com/images/M/MV5BYzYxOTlkYzctNGY2MC00MjNjLWIxOWMtY2QwYjcxZWIwMmEwXkEyXkFqcGc@._V1_SX300.jpg', 9.0, 2011, 0);

INSERT INTO SERIE (STATUS, QTD_TEMPORADAS, ID_IMDB, TITULO, DESCRICAO, POSTER_URL, NOTA_IMDB, ANO_LANCAMENTO, AVALIACAO) VALUES
('Finalizada', 2, 'tt0098936', 'Twin Peaks', 'Um agente idiossincrático do FBI investiga o assassinato de uma jovem na cidade ainda mais idiossincrática de Twin Peaks.', 'https://m.media-amazon.com/images/M/MV5BMTExNzk2NjcxNTNeQTJeQWpwZ15BbWU4MDcxOTczOTIx._V1_SX300.jpg', 8.7, 1990, 0),
('Finalizada', 3, 'tt3322312', 'Daredevil', 'Advogado cego de dia, vigilante à noite. Matt Murdock combate o crime de Nova York como o Demolidor.', 'https://m.media-amazon.com/images/M/MV5BODcwOTg2MDE3NF5BMl5BanBnXkFtZTgwNTUyNTY1NjM@._V1_SX300.jpg', 8.6, 2015, 0),
('Finalizada', 2, 'tt2287229', 'The Pitch', 'Esta série documental leva as câmeras para trás das portas fechadas do mundo da publicidade, enquanto duas agências competem para ganhar uma campanha real de uma grande marca.', 'https://m.media-amazon.com/images/M/MV5BMTk1MDU3ODA1Nl5BMl5BanBnXkFtZTcwNzg3MDM3Nw@@._V1_SX300.jpg', 6.9, 2012, 0),
('Finalizada', 3, 'tt5753856', 'Dark', 'Uma saga familiar com um toque sobrenatural, situada em uma cidade alemã onde o desaparecimento de duas crianças expõe as relações entre quatro famílias.', 'https://m.media-amazon.com/images/M/MV5BOWJjMGViY2UtNTAzNS00ZGFjLWFkNTMtMDBiMDMyZTM1NTY3XkEyXkFqcGc@._V1_SX300.jpg', 8.7, 2017, 0),
('Finalizada', 11, 'tt1442437', 'Modern Family', 'Três famílias diferentes, mas relacionadas, enfrentam provações e tribulações de suas próprias maneiras exclusivamente cômicas.', 'https://m.media-amazon.com/images/M/MV5BYzFlOWFjNzQtODViNC00NzgzLThhZmItZTc1N2VlZDgwODUwXkEyXkFqcGc@._V1_SX300.jpg', 8.5, 2009, 0),
('Finalizada', 8, 'tt0944947', 'Game of Thrones', 'Nove famílias nobres lutam pelo controle das terras de Westeros, enquanto um inimigo antigo retorna após estar adormecido por milênios.', 'https://m.media-amazon.com/images/M/MV5BMTNhMDJmNmYtNDQ5OS00ODdlLWE0ZDAtZTgyYTIwNDY3OTU3XkEyXkFqcGc@._V1_SX300.jpg', 9.2, 2011, 0),
('Finalizada', 8, 'tt2861424', 'Rick and Morty', 'A vida doméstica fragmentada de um cientista louco niilista e seu neto ansioso é ainda mais complicada por suas aventuras interdimensionais.', 'https://m.media-amazon.com/images/M/MV5BZGQyZjk2MzMtMTcyNC00NGU3LTlmNjItNDExMWM4ZDFhYmQ2XkEyXkFqcGc@._V1_SX300.jpg', 9.0, 2013, 0);

